language: node_js
node_js:
   - "0.12.0"

branches:
  only:
    - master
    - dev
    - feature/travis-ci
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success:
  make test-sauce && make test-coveralls

notifications:
    email: false
